name: '[Support] Sync upstream Bitnami changes'
on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 0'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout cloudcops/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: cc
      - name: Checkout bitnami/charts
        run: |
          git clone https://github.com/bitnami/charts bitnami
      - name: Config git user
        run: |
          cd $GITHUB_WORKSPACE/cc
          git config --global user.name "CloudCops bot"
          git config --global user.email "mock@cloudcops.com"
      - name: Copy upstream changes to branch
        run: |
          cd $GITHUB_WORKSPACE/cc/charts
          # Check if the "sync-upstream" branch exists on the remote
          if git ls-remote --heads origin refs/heads/sync-upstream | grep -q 'refs/heads/sync-upstream'; then
              echo "Remote branch 'sync-upstream' exists. Checking it out."
              git fetch
              git checkout --track origin/sync-upstream
          else
              echo "Remote branch 'sync-upstream' not found. Creating and checking out a new local branch."
              git checkout -b sync-upstream
          fi
          # This loop makes it so that archived charts (which are no longer in the charts folder) aren't synced
          for d in */; do
              rsync -a ../../bitnami/bitnami/$d $d
          done
          cd ..
          rsync -a --exclude 'bitnami/' --exclude '.github/' --exclude '.vib/' ../bitnami/ .
          git add -A
          git commit -m "[Cron] Sync Bitnami upstream"
      - name: Commit and push
        run: |
          cd $GITHUB_WORKSPACE/cc
          git config user.name "CloudCops bot"
          git config user.email "mock@cloudcops.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cloudcops/charts
          git push --set-upstream origin sync-upstream
      # - name: Commit and push
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     path: cc
      #     commit-message: "[Cron] Sync Bitnami upstream"
      #     title: "[Cron] Sync Bitnami upstream"
          