name: '[Support] Sync upstream Bitnami changes'
on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 0'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout cloudcops/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: cc
      - name: Checkout bitnami/charts
        run: |
          git clone https://github.com/bitnami/charts bitnami
      - name: Copy upstream changes to new branch
        run: |
          cd $GITHUB_WORKSPACE/cc/charts
          # This loop makes it so that archived charts (which are no longer in the charts folder) aren't synced
          for d in */; do
              rsync -a ../../bitnami/bitnami/$d $d
          done
          cd ..
          rsync -a --exclude 'bitnami/' --exclude '.github/' --exclude '.vib/' ../bitnami/ .
      - name: Commit and push
        run: |
          cd $GITHUB_WORKSPACE/cc
          git config user.name "CloudCops bot"
          git config user.email "mock@cloudcops.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cloudcops/charts
          git checkout -b test
          git add -A
          git commit -m "[Cron] Sync Bitnami upstream"
          git push --set-upstream origin test
      # - name: Commit and push
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     path: cc
      #     commit-message: "[Cron] Sync Bitnami upstream"
      #     title: "[Cron] Sync Bitnami upstream"
          