# This is a GitHub Actions workflow that syncs a fork with its upstream repository.
# It runs on a schedule, fetches changes from the upstream, and creates a pull request.

name: Sync Upstream Fork

on:
  # Trigger the workflow to run weekly at 02:00 on Monday.
  # schedule:
  #   - cron: '0 2 * * 1'
  push:
    branches:
      - main
  
  # Allow the workflow to be run manually from the GitHub Actions tab.
  workflow_dispatch:

jobs:
  sync:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Permissions needed
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Check out the fork's repository.
      # This is necessary for the workflow to access your repo's content.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sync the 'main' branch of the fork with the upstream repository.
      # This step adds the upstream repo as a remote, fetches the changes,
      # and adds them as a branch to our fork. Rebasing will need to happen in the MR in order to merge. This can't happen automatically, because changes could be in conflict.
      - name: Sync fork with upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add the upstream repository as a remote.
          git remote add upstream https://github.com/bitnami/charts.git
          
          # Fetch all branches from the upstream repository.
          git fetch upstream
          
          # Create new branch from upstream's main branch
          git checkout -b sync-upstream upstream/main

          # Restore the .github directory from your fork's main branch
          git checkout origin/main -- .github
          
          # Commit the restored workflows if they were different from upstream's
          # This prevents an error if there are no changes to commit.
          git add .github
          if ! git diff --staged --quiet; then
            git commit -m "Restore fork-specific GitHub Actions workflows"
          fi

          # Push upstream's main branch to out fork
          git push origin sync-upstream

      - name: Diagnose Token Permissions
        run: |
          echo "--- Inspecting token permissions ---"
          gh api repos/${{ github.repository }} --jq .permissions
          echo "------------------------------------"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Create a pull request for changes from the upstream.
      - name: Create pull request
        run: |
          gh pr create --base main --head sync-upstream --title '[Cron] Sync Bitnami upstream' --body 'Created by Github action' --draft
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
