name: '[Support] Sync upstream Bitnami changes'
on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 0'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout cloudcops/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: cc
      - name: Checkout bitnami/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: bitnami/charts
          path: bitnami
      - name: Copy changes to new branch
        run: |
          cd cc/charts
          git checkout -b test
          for d in cc/charts/*/; do
              cp ../../bitnami/bitnami/$d $d
          done
          cd ..
          rsync -av --exclude 'bitnami/' --exclude '.github/' --exclude '.vib/' ../bitnami/ .
          git push