# This is a GitHub Actions workflow that syncs a fork with its upstream repository.
# It runs on a schedule, fetches changes from the upstream, and creates a pull request.

name: Sync Upstream Fork

on:
  # Trigger the workflow to run weekly at 02:00 on Monday.
  # schedule:
  #   - cron: '0 2 * * 1'
  push:
    branches:
      - main
  
  # Allow the workflow to be run manually from the GitHub Actions tab.
  workflow_dispatch:

jobs:
  sync:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Permissions needed
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Check out the fork's repository.
      # This is necessary for the workflow to access your repo's content.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history for a proper merge, not just the last commit.
          fetch-depth: 0

      - name: Backup workflow files
        run: |
          mkdir ../backup
          cp -r .github ../backup

      # Step 2: Sync the 'main' branch of the fork with the upstream repository.
      # This step adds the upstream repo as a remote, fetches the changes,
      # and adds them as a branch to our fork. Rebasing will need to happen in the MR in order to merge. This can't happen automatically, because changes could be in conflict.
      - name: Sync fork with upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add the upstream repository as a remote.
          git remote add upstream https://github.com/bitnami/charts.git
          
          # Fetch all branches from the upstream repository.
          git fetch upstream
          
          # Create new branch from upstream's main branch
          git checkout -b sync-upstream upstream/main

      - name: Restore workflow files
        run: |
          rm -rf .github
          cp -r ../backup/.github .
          git add .github
          git commit -m "Restore workflows"
      - name: Push
        run: |
          # Push upstream's main branch to out fork
          git push origin sync-upstream

      # Step 3: Create a pull request for changes from the upstream.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # The GITHUB_TOKEN is automatically created by Actions and has permissions for this repo.
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # --- Commit and Branch Details ---
          # The commit message for the sync.
          commit-message: "chore: sync from bitnami/charts"
          
          # The author and committer of the sync commit.
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          
          # The name of the branch to create for the pull request.
          branch: "sync-upstream"

          # --- Pull Request Details ---
          # The title of the pull request.
          title: "chore: Sync with upstream bitnami/charts"
          
          # The body content of the pull request.
          body: |
            This is an automated PR to sync this fork with the upstream `bitnami/charts` repository.
            
            It includes the latest changes from the upstream `main` branch.
          
          # Labels to add to the pull request for easy filtering.
          labels: |
            automated-sync
            upstream-sync
            
          # Set to true to delete the branch after the PR is merged or closed.
          delete-branch: true
