name: '[Support] Sync upstream Bitnami changes'
on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 0'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout cloudcops/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: cc
      - name: Checkout bitnami/charts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: bitnami/charts
          path: bitnami
      - name: Copy upstream changes to new branch
        run: |
          cd cc/charts
          git checkout -b test
          # This loop makes it so that archived charts (which are no longer in the charts folder) aren't synced
          for d in */; do
              rsync -a ../../bitnami/bitnami/$d $d
          done
          cd ..
          rsync -a --exclude 'bitnami/' --exclude '.github/' --exclude '.vib/' ../bitnami/ .
      - name: Commit and push
        run: |
          cd cc
          git config user.name "CloudCops Bot"
          git config user.email "mock@cloudcops.com"
          git add -A
          git commit -m "[Cron] Sync Bitnami upstream"
          git push --set-upstream origin test